### PR TITLE
Archive document-download-frontend

### PR DESCRIPTION
**Pull request by sastels**
# Summary | Résumé

ADR regarding archiving `document-download-frontend`.

# Help requested | Aide requise

Please review, comment and suggest.

### CODE REVIEW

**Comment by jimleroyer** [comment]
I spoke to Antoine about this and he said he kept the front-end in case that we still needed it, i.e. this might happen in the near future that we will have to bring back a download front-end in order to provide users more information, have confirmation or for more advanced user's verification. In the meantime though, we could totally shut down the front-end to eliminate maintenance effort on it.

**Comment by yaelberger-commits** [comment]
Just needs a review to decide if we want to do this or not

**Comment by yaelberger-commits** [comment]
Decided yes from ADR

**Review by jimleroyer — APPROVED** [review]
Let's update the status decision sections and merge it!

**Pull request merged**
